### ISSUE TITLE
Блок дработок

### ISSUE THREAD

**Issue by zverev-git** [LamaEats/flatcontrol#11]
- [x] Вернее меню (акции) пункты имеют active элемент и не имеют :hover для неактивных
- [x] В подвале предлагаю отцентровать по вертикали логотип
- [x] Страница ленты новостей - под кнопкой «Больше новостей» сделать обычную пагинацию по центру, в итоге получится как в маркете. + страница акций
- [x] Блок хода строительства(фотоотчеты):
 - Надо продумать отображение не трех месяцев, а 1-2 так как при запуске не будет столько отчетов. 
 - Активным отчетом будет всегда крайний правый. 
- [x] на мобильных устройствах не отображаются параметры объекта. Их нужно выводить после изображения

**Comment by LamaEats** [comment]
п3 + для страницы акций

**Comment by LamaEats** [comment]
готово
